Repository BinaryStudioAcademy/bsa-winter-2021-2022-bws, pull requests merged in 2022-02, with the labels that each got.

#3 Task/bws20 master sign in
  backend/src/validation-schemas/master/master.ts
  backend/src/validation-schemas/validation-schemas.ts
  frontend/src/common/types/master/master.ts
  frontend/src/common/types/types.ts
  frontend/src/components/auth/auth.tsx
  frontend/src/components/auth/components/sign-in-form/common/constants.ts
  frontend/src/components/auth/components/sign-in-form/common/sign-in-form.module.scss
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/common.ts
  frontend/src/validation-schemas/master/master.ts
  frontend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/validation/master/master-validation-message.ts
  shared/src/common/enums/validation/master/master.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/types/master/master-sign-in-dto.type.ts
  shared/src/common/types/master/master.ts
  shared/src/common/types/types.ts
  shared/src/validation/master/master-sign-in/master-sign-in.validation-schema.ts
  shared/src/validation/master/master-sign-up/master-sign-up.validation-schema.ts
  shared/src/validation/master/master.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement

#5 BWS-32: + added common component table
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/common.ts
  frontend/src/components/common/table/table.module.scss
  frontend/src/components/common/table/table.tsx
Labels: enhancement

#7 BWS-40: + insert permissions
  backend/src/common/enums/enums.ts
  backend/src/common/enums/permissions/permissions.ts
  backend/src/data/migrations/20220207071214_edit_permissions_table.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/permissions/permission.enum.ts
  shared/src/common/enums/permissions/permissions.ts
Labels: enhancement

#10 Task/bws41 make tenantid not nullable in masters db table
  backend/src/data/migrations/20220207134835_edit_masters_tenant_id.ts
Labels: enhancement

#12 Task/bws37 private routes
  frontend/src/components/app/app.tsx
  frontend/src/components/auth/auth.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/private-route/private-route.tsx
  frontend/src/components/dashboard/dashboard.tsx
  frontend/src/services/navigation/navigation.service.ts
  frontend/src/services/services.ts
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/reducer.ts
  frontend/src/store/store.ts
Labels: enhancement

#18 BWS-35: + error handling
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/img/attention-icon.svg
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/toaster/toaster.tsx
  frontend/src/services/notifications/notification.module.scss
  frontend/src/services/notifications/notification.service.tsx
  frontend/src/services/services.ts
  frontend/src/store/middlewares/handle-error/handle-error.middleware.ts
  frontend/src/store/middlewares/middlewares.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/store.ts
Labels: merge conflicts

#19 Fix/bws37 private routes
  frontend/src/components/app/app.tsx
Labels: enhancement

#17 Task/bws36 auto create tenant
  backend/src/common/types/tenant/tenant.ts
  backend/src/common/types/types.ts
  backend/src/data/migrations/20220208161915_edit_tenants_create_at.ts
  backend/src/data/models/master/master-table-field.enum.ts
  backend/src/data/models/master/master.model.ts
  backend/src/data/models/models.ts
  backend/src/data/models/tenant/tenant-table-field.enum.ts
  backend/src/data/models/tenant/tenant.model.ts
  backend/src/data/repositories/master/master.repository.ts
  backend/src/data/repositories/repositories.ts
  backend/src/data/repositories/tenant/tenant.repository.ts
  backend/src/services/master/master.entity.ts
  backend/src/services/master/master.service.ts
  backend/src/services/services.ts
  backend/src/services/tenant/tenant.entity.ts
  backend/src/services/tenant/tenant.service.ts
  shared/src/common/types/tenant/tenant-dto.type.ts
  shared/src/common/types/tenant/tenant.ts
  shared/src/common/types/types.ts
Labels: enhancement

#14 Task/bws16 master sign in
  backend/src/api/masters/masters.api.ts
  backend/src/common/enums/enums.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/enums/exception/exception.ts
  backend/src/common/types/master/master.ts
  backend/src/common/types/types.ts
  backend/src/services/encrypt/encrypt.service.ts
  backend/src/services/master/master.service.ts
  frontend/src/common/types/master/master.ts
  frontend/src/common/types/types.ts
  frontend/src/components/auth/auth.tsx
  frontend/src/components/auth/components/sign-in-form/common/constants.ts
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/store/auth/actions.ts
  shared/src/common/types/master/master-sign-in-dto.type.ts
  shared/src/common/types/master/master-sign-in-request-dto.type.ts
  shared/src/common/types/master/master-sign-in-response-dto.type.ts
  shared/src/common/types/master/master.ts
  shared/src/common/types/types.ts
  shared/src/validation/master/master-sign-in/master-sign-in.validation-schema.ts
Labels: enhancement

#22 BWS-15: * fix bug
  frontend/src/assets/img/decorate.svg
  frontend/src/assets/img/network.svg
  frontend/src/components/auth/auth.module.scss
Labels: bug

#37 Task/bws54 workers table
  backend/src/api/api.ts
  backend/src/api/eam/eam.api.ts
  backend/src/common/types/types.ts
  backend/src/common/types/worker/worker.ts
  backend/src/data/models/worker/worker.model.ts
  backend/src/data/repositories/repositories.ts
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/services/services.ts
  backend/src/services/worker/worker.service.ts
  shared/src/common/enums/api/eam-api-path.enum.ts
  shared/src/common/types/eam-worker/eam-worker-get-all-item-response-dto.type.ts
  shared/src/common/types/eam-worker/eam-worker-get-all-response-dto.type.ts
  shared/src/common/types/eam-worker/eam-worker.ts
  shared/src/common/types/types.ts
Labels: enhancement

#42 BWS-60: + logout
  frontend/src/components/common/header/header.tsx
  frontend/src/services/storage/storage.service.tsx
  frontend/src/store/auth/actions.ts
  frontend/src/store/auth/common.ts
  frontend/src/store/auth/reducer.ts
Labels: enhancement

#55 Task/bws9 dashboard
  frontend/src/assets/css/variables.scss
  frontend/src/assets/img/binary-storage.svg
  frontend/src/assets/img/dashboard-decorate.svg
  frontend/src/assets/img/eam.svg
  frontend/src/assets/img/server-computing.svg
  frontend/src/assets/img/sl-computing.svg
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/types/ui/service-menu.ts
  frontend/src/components/auth/components/sign-in-form/sign-in-form.module.scss
  frontend/src/components/auth/components/sign-up-form/sign-up-form.module.scss
  frontend/src/components/auth/components/sign-up-form/sign-up-form.tsx
  frontend/src/components/common/button/button.module.scss
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/link/link.tsx
  frontend/src/components/dashboard/components/services-item/services-item.tsx
  frontend/src/components/dashboard/components/services-item/styles.module.scss
  frontend/src/components/dashboard/components/services-list/services-list.tsx
  frontend/src/components/dashboard/components/services-list/styles.module.scss
  frontend/src/components/dashboard/constants/constans.ts
  frontend/src/components/dashboard/dashboard.tsx
  frontend/src/components/dashboard/styles.module.scss
Labels: enhancement

#57 BWS-9: * sign in color and margins in service cards
  frontend/src/components/auth/components/sign-in-form/sign-in-form.tsx
  frontend/src/components/common/button/button.module.scss
  frontend/src/components/dashboard/components/services-item/styles.module.scss
Labels: bug

#21 BWS-52: + front and validation
  frontend/src/common/enums/api/api.ts
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/types/types.ts
  frontend/src/common/types/worker/worker.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/button/button.module.scss
  frontend/src/components/common/input/input.module.scss
  frontend/src/components/dashboard/styles.module.scss
  frontend/src/components/eam-create-worker/common/constants.ts
  frontend/src/components/eam-create-worker/eam-create-worker.module.scss
  frontend/src/components/eam-create-worker/eam-create-worker.tsx
  frontend/src/components/eam/eam.module.scss
  frontend/src/components/eam/eam.tsx
  frontend/src/helpers/helpers.ts
  frontend/src/helpers/typescript/typescript.ts
  frontend/src/services/services.ts
  frontend/src/services/worker-api/worker-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/eam-worker-configurate/actions.ts
  frontend/src/store/eam-worker-configurate/common.ts
  frontend/src/store/eam-worker-configurate/eam-worker-configurate.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/store.ts
  frontend/src/validation-schemas/validation-schemas.ts
  frontend/src/validation-schemas/worker/worker.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/enums/validation/worker/create-worker-validation-rule.enum.ts
  shared/src/common/enums/validation/worker/worker-validation-message.ts
  shared/src/common/enums/validation/worker/worker.ts
  shared/src/common/types/types.ts
  shared/src/common/types/worker/eam-worker-create-form-dto.type.ts
  shared/src/common/types/worker/worker.ts
  shared/src/validation/eam-worker/worker-create/worker-create.validation-schema.ts
  shared/src/validation/eam-worker/worker.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement, merge conflicts

#59 BWS-9: * button styles
  frontend/src/assets/css/variables.scss
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/ui/button-color.enum.ts
  frontend/src/common/enums/ui/ui.ts
  frontend/src/components/common/button/button.module.scss
  frontend/src/components/common/button/button.tsx
  frontend/src/components/dashboard/components/services-item/services-item.tsx
Labels: bug

#58 Task/bws54 workers table
  backend/src/api/eam/eam.api.ts
  backend/src/common/enums/api/api.ts
  backend/src/common/enums/enums.ts
  backend/src/common/types/eam-worker/eam-worker.ts
  backend/src/common/types/types.ts
  backend/src/data/models/worker/worker-table-field.enum.ts
  backend/src/data/models/worker/worker.model.ts
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/services/worker/worker.service.ts
  frontend/src/common/enums/api/api.ts
  frontend/src/common/enums/eam/eam.ts
  frontend/src/common/enums/eam/table/table.ts
  frontend/src/common/enums/eam/table/workers-table-accessor.enum.ts
  frontend/src/common/enums/eam/table/workers-table-header.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/types/eam-worker/eam-worker.ts
  frontend/src/common/types/types.ts
  frontend/src/common/types/worker/worker.ts
  frontend/src/components/eam/components/components.ts
  frontend/src/components/eam/components/workers-table/helpers/get-columns.helper.ts
  frontend/src/components/eam/components/workers-table/helpers/get-rows.helper.ts
  frontend/src/components/eam/components/workers-table/helpers/helpers.ts
  frontend/src/components/eam/components/workers-table/workers-table.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/components/eam/styles.module.scss
  frontend/src/services/eam-api/eam-api.service.ts
  frontend/src/store/eam/actions.ts
  frontend/src/store/eam/common.ts
  frontend/src/store/eam/reducer.ts
  shared/src/common/enums/api/api.ts
  shared/src/common/enums/api/workers-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/types/eam-worker/eam-worker-get-all-item-response-dto.type.ts
  shared/src/common/types/eam-worker/eam-worker-get-by-tenant-request-params-dto.type.ts
  shared/src/common/types/eam-worker/eam-worker-groups-item.type.ts
  shared/src/common/types/eam-worker/eam-worker.ts
  shared/src/common/types/types.ts
Labels: enhancement

#63 BWS-67: + validation on create group api
  backend/src/api/eam/eam.api.ts
  backend/src/validation-schemas/eam-group/eam-group.ts
  backend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/validation/eam-group/eam-group-validation-massage.ts
  shared/src/common/enums/validation/eam-group/eam-group-validation-rule.enum.ts
  shared/src/common/enums/validation/eam-group/eam-group.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/enums/validation/worker/worker-validation-message.ts
  shared/src/validation/eam-group/eam-group-create/group-create.validation-schema.ts
  shared/src/validation/eam-group/eam-group.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement

#68 BWS-24: + migrations for bs spaces and objects
  backend/src/common/enums/db/table-name.enum.ts
  backend/src/data/migrations/20220216121833_add_binary_storage_spaces_table.ts
  backend/src/data/migrations/20220216131912_add_binary_storage_objects_table.ts
Labels: enhancement

#72 BWS-52: * validation message
  shared/src/common/enums/validation/worker/worker-validation-message.ts
Labels: enhancement

#75 BWS-52: + groups table in eam/create/worker page
  frontend/src/components/eam-create-worker/eam-create-worker.module.scss
  frontend/src/components/eam-create-worker/eam-create-worker.tsx
  frontend/src/components/eam-create-worker/helpers/get-columns-helper/cells/celect-row-cell/select-row-cell.tsx
  frontend/src/components/eam-create-worker/helpers/get-columns-helper/cells/cells.ts
  frontend/src/components/eam-create-worker/helpers/get-columns-helper/get-columns.helper.tsx
  frontend/src/components/eam-create-worker/helpers/get-rows.helper.ts
  frontend/src/components/eam-create-worker/helpers/helpers.ts
  frontend/src/store/eam-worker-configurate/actions.ts
  frontend/src/store/eam-worker-configurate/common.ts
  frontend/src/store/eam-worker-configurate/eam-worker-configurate.ts
  frontend/src/store/eam-worker-configurate/reducer.ts
  frontend/src/store/root-reducer.ts
Labels: enhancement

#78 BWS-52: * validation message and rules
  shared/src/common/enums/validation/worker/create-worker-validation-rule.enum.ts
  shared/src/common/enums/validation/worker/worker-validation-message.ts
Labels: enhancement

#80 BWS-52: rename title
  frontend/src/components/eam-create-worker/eam-create-worker.tsx
Labels: enhancement

#79 Task/bws24 bs create space backend
  .env.example/backend.env
  backend/package-lock.json
  backend/package.json
  backend/src/api/api.ts
  backend/src/api/bs/bs.api.ts
  backend/src/common/enums/api/api.ts
  backend/src/common/enums/app/env.enum.ts
  backend/src/common/enums/enums.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/bs-space/bs-space.ts
  backend/src/common/types/types.ts
  backend/src/data/models/models.ts
  backend/src/data/models/space/space-table-field.enum.ts
  backend/src/data/models/space/space.model.ts
  backend/src/data/repositories/repositories.ts
  backend/src/data/repositories/space/space.repository.ts
  backend/src/services/aws/s3/s3.service.ts
  backend/src/services/services.ts
  backend/src/services/space/space.entity.ts
  backend/src/services/space/space.service.ts
  backend/src/validation-schemas/bs-space/bs-space.ts
  backend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/api/api-path.enum.ts
  shared/src/common/enums/api/api.ts
  shared/src/common/enums/api/bs-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/http/http-code.enum.ts
  shared/src/common/enums/validation/bs-space/bs-space-validation-massage.ts
  shared/src/common/enums/validation/bs-space/bs-space-validation-rule.enum.ts
  shared/src/common/enums/validation/bs-space/bs-space.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/types/bs-space/bs-space-create-request-dto.type.ts
  shared/src/common/types/bs-space/bs-space.ts
  shared/src/common/types/types.ts
  shared/src/validation/bs-space/bs-space-create/space-create.validation-shema.ts
  shared/src/validation/bs-space/bs-space.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement

#77 Task/bws92 master should return with array of the permission from repository should be unique only
  backend/src/common/types/eam-master/eam-master.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/master/master.repository.ts
  backend/src/data/repositories/repositories.ts
  backend/src/services/master/master.entity.ts
  backend/src/services/master/master.service.ts
  shared/src/common/types/eam-master/eam-master-by-id-response-dto.type.ts
  shared/src/common/types/eam-master/eam-master-permissions-item-dto.type.ts
  shared/src/common/types/eam-master/eam-master.ts
  shared/src/common/types/types.ts
Labels: enhancement

#84 BWS-24: + bs and space creation page
  backend/src/api/bs/bs.api.ts
  frontend/src/common/enums/api/api.ts
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/types/bs-space/bs-space.ts
  frontend/src/common/types/types.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/bs-create-space/bs-create-space.module.scss
  frontend/src/components/bs-create-space/bs-create-space.tsx
  frontend/src/components/bs-create-space/common/constants.ts
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/styles.module.scss
  frontend/src/services/bs-api/bs-api.service.ts
  frontend/src/services/services.ts
  frontend/src/store/actions.ts
  frontend/src/store/bs-space-create/actions.ts
  frontend/src/store/bs-space-create/common.ts
  frontend/src/store/bs-space-create/reducer.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/store.ts
  frontend/src/validation-schemas/bs-space/bs-space.ts
  frontend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/api/bs-api-path.enum.ts
  shared/src/common/types/bs-space/bs-space-create-form-dto.type.ts
  shared/src/common/types/bs-space/bs-space-create-response-dto.type.ts
  shared/src/common/types/bs-space/bs-space.ts
  shared/src/common/types/types.ts
Labels: enhancement

#88 BWS-104: + group table in eam/create/worker page
  frontend/src/common/enums/eam/table/groups-table-accessor.enum.ts
  frontend/src/components/eam-create-worker/helpers/get-columns-helper/get-columns.helper.tsx
  frontend/src/components/eam-create-worker/helpers/get-rows.helper.ts
Labels: enhancement

#89 Task/bws24 buckets list by current tenant
  backend/src/api/bs/bs.api.ts
  backend/src/common/types/bs-space/bs-space.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/space/space.repository.ts
  backend/src/services/space/space.service.ts
  frontend/src/common/enums/bs/bs.ts
  frontend/src/common/enums/bs/table/spaces-table-accessor.enum.ts
  frontend/src/common/enums/bs/table/spaces-table-header.enum.ts
  frontend/src/common/enums/bs/table/table.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/types/bs-space/bs-space.ts
  frontend/src/common/types/types.ts
  frontend/src/components/bs-create-space/bs-create-space.tsx
  frontend/src/components/bs-create-space/styles.module.scss
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/components/components.ts
  frontend/src/components/bs/components/spaces-table/helpers/get-columns.helper.ts
  frontend/src/components/bs/components/spaces-table/helpers/get-rows.helper.ts
  frontend/src/components/bs/components/spaces-table/helpers/helpers.ts
  frontend/src/components/bs/components/spaces-table/spaces-table.tsx
  frontend/src/components/bs/styles.module.scss
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
  frontend/src/components/eam-configurate-group/styles.module.scss
  frontend/src/components/eam-create-worker/eam-create-worker.tsx
  frontend/src/components/eam-create-worker/styles.module.scss
  frontend/src/services/bs-api/bs-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/bs/actions.ts
  frontend/src/store/bs/common.ts
  frontend/src/store/bs/reducer.ts
  frontend/src/store/root-reducer.ts
  shared/src/common/types/bs-space/bs-space-get-filter.type.ts
  shared/src/common/types/bs-space/bs-space-get-request-params-dto.type.ts
  shared/src/common/types/bs-space/bs-space-get-responce-item-dto.type.ts
  shared/src/common/types/bs-space/bs-space-get-response-dto.type.ts
  shared/src/common/types/bs-space/bs-space.ts
  shared/src/common/types/token/token-payload.type.ts
  shared/src/common/types/types.ts
Labels: enhancement

#82 BWS-100: + dateFormat
  frontend/src/components/eam/components/groups-table/helpers/get-rows.helper.ts
  frontend/src/components/eam/components/workers-table/helpers/get-rows.helper.ts
  frontend/src/helpers/date/date.ts
  frontend/src/helpers/helpers.ts
  shared/src/common/enums/date/date-format.enum.ts
  shared/src/common/enums/date/date-format.ts
  shared/src/common/enums/enums.ts
  shared/src/helpers/date/date.ts
  shared/src/helpers/date/get-distance-to-date-now/get-distance-to-date-now.ts
  shared/src/helpers/date/get-formatted-date/get-formatted-date.ts
  shared/src/helpers/helpers.ts
Labels: enhancement

#94 BWS-100: + data-format-in-the-created-at-column
  frontend/src/components/eam-create-worker/helpers/get-rows.helper.ts
Labels: enhancement

#93 BWS-99: + success-messages
  frontend/.stylelintrc.yml
  frontend/src/assets/css/variables.scss
  frontend/src/services/notification/notification.module.scss
  frontend/src/services/notification/notification.service.tsx
Labels: enhancement

#96 bws-107: + migration for make tenantId not nullable
  backend/src/data/migrations/20220222084102_edit_worker_tenant_id.ts
Labels: enhancement

#101 Task/bws21 add table of functions to slc service
  backend/src/api/slc/slc.api.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/slc-function/slc-function.repository.ts
  backend/src/services/slc-function/slc-function.service.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/slc/slc.ts
  frontend/src/common/enums/slc/table/functions-table-accessor.enum.ts
  frontend/src/common/enums/slc/table/functions-table-header.enum.ts
  frontend/src/common/enums/slc/table/table.ts
  frontend/src/common/types/slc-function/slc-function.ts
  frontend/src/common/types/types.ts
  frontend/src/components/slc/components/components.ts
  frontend/src/components/slc/components/functions-table/functions-table.tsx
  frontend/src/components/slc/components/functions-table/helpers/get-columns.helper.ts
  frontend/src/components/slc/components/functions-table/helpers/get-rows.helper.ts
  frontend/src/components/slc/components/functions-table/helpers/helpers.ts
  frontend/src/components/slc/slc.tsx
  frontend/src/components/slc/styles.module.scss
  frontend/src/services/slc-api/slc-api.service.ts
  frontend/src/store/actions.ts
  frontend/src/store/root-reducer.ts
  frontend/src/store/slc/actions.ts
  frontend/src/store/slc/common.ts
  frontend/src/store/slc/reducer.ts
  shared/src/common/types/slc-function/slc-function-get-filter.type.ts
  shared/src/common/types/slc-function/slc-function-get-request-params-dto.type.ts
  shared/src/common/types/slc-function/slc-function-get-responce-item-dto.type.ts
  shared/src/common/types/slc-function/slc-function-get-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
Labels: enhancement

#100 fix/bws68-validation worker
  backend/src/api/eam/eam.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/services/worker/worker.service.ts
  backend/src/validation-schemas/eam-worker/eam-worker.ts
  backend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-message.ts
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-rule.enum.ts
  shared/src/common/enums/validation/eam-worker/eam-worker.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/enums/validation/worker/worker.ts
  shared/src/validation/eam-worker/eam-worker-create-backend/eam-worker-create.validation-schema.ts
  shared/src/validation/eam-worker/eam-worker.ts
  shared/src/validation/eam-worker/worker.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement, merge conflicts

#107 Task/bws 74 server error messages sign in worker form
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/data/repositories/tenant/tenant.repository.ts
  backend/src/services/services.ts
  backend/src/services/worker/worker.service.ts
Labels: enhancement

#102 Task/bws110 delete bucket
  backend/src/api/bs/bs.api.ts
  backend/src/common/enums/api/api.ts
  backend/src/common/enums/enums.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/bs-space/bs-space.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/space/space.repository.ts
  backend/src/exceptions/bs-error/bs-error.ts
  backend/src/exceptions/exceptions.ts
  backend/src/services/aws/s3/s3.service.ts
  backend/src/services/master/master.service.ts
  backend/src/services/space/space.service.ts
  backend/src/services/worker/worker.service.ts
  frontend/src/assets/img/delete-icon.svg
  frontend/src/common/enums/api/api.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/types/bs-space/bs-space.ts
  frontend/src/common/types/types.ts
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/components/spaces-table/helpers/cells/cells.ts
  frontend/src/components/bs/components/spaces-table/helpers/cells/delete-row-cell/delete-row-cell.tsx
  frontend/src/components/bs/components/spaces-table/helpers/cells/delete-row-cell/styles.module.scss
  frontend/src/components/bs/components/spaces-table/helpers/get-columns.helper.ts
  frontend/src/components/bs/components/spaces-table/helpers/get-rows.helper.ts
  frontend/src/components/bs/components/spaces-table/spaces-table.tsx
  frontend/src/services/bs-api/bs-api.service.ts
  frontend/src/store/bs/actions.ts
  frontend/src/store/bs/common.ts
  frontend/src/store/bs/reducer.ts
  shared/src/common/enums/api/api.ts
  shared/src/common/enums/api/spaces-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/http/http-method.enum.ts
  shared/src/common/types/bs-space/bs-space-delete-request-dto.type.ts
  shared/src/common/types/bs-space/bs-space-get-responce-item-dto.type.ts
  shared/src/common/types/bs-space/bs-space.ts
  shared/src/common/types/types.ts
Labels: enhancement

#108 Fix/bws114 displayed permissions
  frontend/src/components/app/app.tsx
  frontend/src/components/eam-configurate-worker/common/constants.ts
  frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
  frontend/src/components/eam-configurate-worker/helpers/get-columns-helper/cells/cells.ts
  frontend/src/components/eam-configurate-worker/helpers/get-columns-helper/cells/select-row-cell/select-row-cell.tsx
  frontend/src/components/eam-configurate-worker/helpers/get-columns-helper/get-columns.helper.tsx
  frontend/src/components/eam-configurate-worker/helpers/get-rows.helper.ts
  frontend/src/components/eam-configurate-worker/helpers/helpers.ts
  frontend/src/components/eam-configurate-worker/styles.module.scss
  frontend/src/components/eam-create-worker/helpers/get-columns-helper/cells/cells.ts
Labels: enhancement

#106 Task/bws21 add delete function functionality
  backend/src/api/slc/slc.api.ts
  backend/src/common/enums/api/api.ts
  backend/src/common/enums/enums.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/slc-function/slc-function.repository.ts
  backend/src/services/aws/lambda/lambda.service.ts
  backend/src/services/slc-function/slc-function.service.ts
  frontend/src/common/enums/api/api.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/notification/notification-message.enum.ts
  frontend/src/common/enums/notification/notification-title.enum.ts
  frontend/src/common/enums/notification/notification.ts
  frontend/src/common/enums/slc/table/functions-table-accessor.enum.ts
  frontend/src/common/enums/slc/table/functions-table-header.enum.ts
  frontend/src/components/slc/components/functions-table/functions-table.tsx
  frontend/src/components/slc/components/functions-table/helpers/cells/cells.ts
  frontend/src/components/slc/components/functions-table/helpers/cells/delete-row-cell/delete-row-cell.tsx
  frontend/src/components/slc/components/functions-table/helpers/cells/delete-row-cell/styles.module.scss
  frontend/src/components/slc/components/functions-table/helpers/get-columns.helper.ts
  frontend/src/components/slc/components/functions-table/helpers/get-rows.helper.ts
  frontend/src/components/slc/slc.tsx
  frontend/src/services/slc-api/slc-api.service.ts
  frontend/src/store/bs-space-create/actions.ts
  frontend/src/store/bs/actions.ts
  frontend/src/store/eam-group-configurate/actions.ts
  frontend/src/store/eam-worker-configurate/actions.ts
  frontend/src/store/sc-configurate-instance/actions.ts
  frontend/src/store/slc-configurate-function/actions.ts
  frontend/src/store/slc/actions.ts
  frontend/src/store/slc/common.ts
  frontend/src/store/slc/reducer.ts
  shared/src/common/enums/api/api.ts
  shared/src/common/enums/api/slc-function-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/types/slc-function/slc-function-delete-params-dto.type.ts
  shared/src/common/types/slc-function/slc-function-get-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function-get-response-item-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
Labels: enhancement

#109 bws-101: * created-at-column-title
  frontend/src/common/enums/eam/table/groups-table-header.enum.ts
  frontend/src/common/enums/eam/table/workers-table-header.enum.ts
Labels: enhancement
