Repository BinaryStudioAcademy/bsa-winter-2021-2022-bws, pull requests merged in 2022-03, with the labels that each got.

#117 BWS-116: * validation message
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-rule.enum.ts
  shared/src/validation/eam-worker/eam-worker-sign-in/eam-worker-sign-in.validation-schema.ts
Labels: enhancement

#111 BWS-78: + backend and frontend
  backend/src/api/tenants/tenants.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/eam-tenant-update/eam-tenant-update.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/tenant/tenant.repository.ts
  backend/src/exceptions/exceptions.ts
  backend/src/exceptions/tenant-error/tenant-error.ts
  backend/src/services/tenant/tenant.entity.ts
  backend/src/services/tenant/tenant.service.ts
  backend/src/validation-schemas/eam-tenant-update/eam-tenant-update.ts
  backend/src/validation-schemas/validation-schemas.ts
  frontend/src/common/enums/notification/notification-message.enum.ts
  frontend/src/common/types/eam-tenant/eam-tenant.ts
  frontend/src/common/types/types.ts
  frontend/src/components/eam/components/components.ts
  frontend/src/components/eam/components/tenant/helpers/helpers.ts
  frontend/src/components/eam/components/tenant/helpers/tenant-default-values.helper.ts
  frontend/src/components/eam/components/tenant/styles.module.scss
  frontend/src/components/eam/components/tenant/tenant.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/hooks/use-app-form/use-app-form.hook.ts
  frontend/src/services/tenant-api/tenant-api.service.ts
  frontend/src/store/app/reducer.ts
  frontend/src/store/eam/actions.ts
  frontend/src/store/eam/common.ts
  frontend/src/validation-schemas/eam-tenant/eam-tenant.ts
  frontend/src/validation-schemas/validation-schemas.ts
  shared/src/common/enums/api/tenants-api-path.enum.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/validation/bs-space/bs-space-validation-message.ts
  shared/src/common/enums/validation/bs-space/bs-space.ts
  shared/src/common/enums/validation/eam-group/eam-group-validation-message.ts
  shared/src/common/enums/validation/eam-group/eam-group.ts
  shared/src/common/enums/validation/eam-tenant/eam-tenant-validation-message.ts
  shared/src/common/enums/validation/eam-tenant/eam-tenant-validation-rule.enum.ts
  shared/src/common/enums/validation/eam-tenant/eam-tenant.ts
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-rule.enum.ts
  shared/src/common/enums/validation/validation.ts
  shared/src/common/types/eam-tenant/eam-tenant-form-dto.type.ts
  shared/src/common/types/eam-tenant/eam-tenant-update-request-dto.type.ts
  shared/src/common/types/eam-tenant/eam-tenant.ts
  shared/src/common/types/types.ts
  shared/src/validation/eam-tenant-update/eam-tenant-update.validation-schema.ts
  shared/src/validation/validation-schemas.ts
Labels: enhancement

#118 BWS-78: * notification message
  frontend/src/common/enums/notification/notification-message.enum.ts
Labels: enhancement

#119 BWS-76: * message
  frontend/src/common/enums/notification/notification-message.enum.ts
Labels: enhancement

#123 Task/bws 126 + edit slc function code to backend
  backend/src/api/slc/slc.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/slc-function/slc-function.repository.ts
  backend/src/services/aws/lambda/lambda.service.ts
  backend/src/services/slc-function/slc-function.entity.ts
  backend/src/services/slc-function/slc-function.service.ts
  backend/src/validation-schemas/eam-group/eam-group.ts
  backend/src/validation-schemas/eam-master/eam-master.ts
  backend/src/validation-schemas/eam-tenant-update/eam-tenant-update.ts
  backend/src/validation-schemas/eam-worker/eam-worker.ts
  frontend/src/validation-schemas/eam-master/eam-master.ts
  frontend/src/validation-schemas/eam-tenant/eam-tenant.ts
  shared/src/common/enums/http/http-method.enum.ts
  shared/src/common/types/slc-function/slc-function-update-params-dto.type.ts
  shared/src/common/types/slc-function/slc-function-update-request-dto.type.ts
  shared/src/common/types/slc-function/slc-function-update-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
Labels: enhancement

#127 BWS-81: + delete worker
  backend/src/api/eam/eam.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/eam-worker/eam-worker.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/exceptions/eam-error/eam-error.ts
  backend/src/exceptions/exceptions.ts
  backend/src/services/worker/worker.service.ts
  shared/src/common/enums/api/workers-api-path.enum.ts
  shared/src/common/types/eam-worker/eam-worker-delete-request-dto.type.ts
  shared/src/common/types/eam-worker/eam-worker.ts
  shared/src/common/types/types.ts
Labels: enhancement

#138 BWS-130: + instance auto deleting
  .env.example/backend.env
  backend/src/common/enums/app/env.enum.ts
  backend/src/data/repositories/instance/instance.repository.ts
  backend/src/server.ts
  backend/src/services/background/old-instances-auto-deleting/old.insnaces.bj.service.ts
  backend/src/services/services.ts
Labels: enhancement

#141 Revert "BWS-130: + instance auto deleting"
  .env.example/backend.env
  backend/src/common/enums/app/env.enum.ts
  backend/src/data/repositories/instance/instance.repository.ts
  backend/src/server.ts
  backend/src/services/background/old-instances-auto-deleting/old.insnaces.bj.service.ts
  backend/src/services/services.ts
Labels: help wanted

#140 BWS-102: + group and worker name validation
  shared/src/common/enums/validation/eam-group/eam-group-validation-message.ts
  shared/src/common/enums/validation/eam-group/eam-group-validation-rule.enum.ts
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-message.ts
  shared/src/common/enums/validation/eam-worker/eam-worker-create-validation-rule.enum.ts
  shared/src/validation/eam-worker/eam-worker-create-backend/eam-worker-create.validation-schema.ts
  shared/src/validation/eam-worker/eam-worker-create/eam-worker-create.validation-schema.ts
  shared/src/validation/eam-worker/eam-worker-sign-in/eam-worker-sign-in.validation-schema.ts
Labels: enhancement

#126 Task/bws 126 add endpoint
  backend/src/api/slc/slc.api.ts
  backend/src/common/enums/lambda-default-param/lambda-default-param.enum.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/services/slc-function/slc-function.entity.ts
  backend/src/services/slc-function/slc-function.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/types/slc-function/slc-function.ts
  frontend/src/common/types/types.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/editor/editor.tsx
  frontend/src/components/common/loader/loader.module.scss
  frontend/src/components/slc-configurate-function/components/components.ts
  frontend/src/components/slc-configurate-function/components/create-form/create-form.tsx
  frontend/src/components/slc-configurate-function/components/create-form/styles.module.scss
  frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
  frontend/src/components/slc-configurate-function/components/edit-form/styles.module.scss
  frontend/src/components/slc-configurate-function/slc-configurate-function.tsx
  frontend/src/components/slc-configurate-function/styles.module.scss
  frontend/src/components/slc/components/functions-table/components/action-cell/action-cell.tsx
  frontend/src/components/slc/components/functions-table/components/action-cell/styles.module.scss
  frontend/src/components/slc/components/functions-table/helpers/get-rows.helper.ts
  frontend/src/services/slc-api/slc-api.service.ts
  frontend/src/store/slc-configurate-function/actions.ts
  frontend/src/store/slc-configurate-function/common.ts
  frontend/src/store/slc-configurate-function/reducer.ts
  shared/src/common/types/slc-function/slc-function-load-params-dto.type.ts
  shared/src/common/types/slc-function/slc-function-load-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
Labels: enhancement, action error

#142 Task/bws130 instance auto deleting
  .env.example/backend.env
  backend/src/common/constants/background-job.constants.ts
  backend/src/common/constants/constants.ts
  backend/src/common/enums/app/env.enum.ts
  backend/src/data/repositories/instance/instance.repository.ts
  backend/src/helpers/date/date.ts
  backend/src/helpers/helpers.ts
  backend/src/server.ts
  backend/src/services/background/background-job.ts
  backend/src/services/services.ts
  shared/src/helpers/date/date.ts
  shared/src/helpers/date/sub-hours/sub-hours.helper.ts
  shared/src/helpers/helpers.ts
Labels: enhancement

#149 Task/bws79 table cell overflow
  frontend/src/components/common/table/styles.module.scss
Labels: enhancement

#150 BWS-146: + reload instances
  frontend/src/assets/img/reload-icon.svg
  frontend/src/common/enums/ui/icon-name.enum.ts
  frontend/src/components/common/button/button.tsx
  frontend/src/components/sc/sc.tsx
  frontend/src/components/sc/styles.module.scss
Labels: enhancement

#147 Task/bws 97 table placeholder
  frontend/src/components/bs/components/spaces-table/spaces-table.tsx
  frontend/src/components/common/table/styles.module.scss
  frontend/src/components/common/table/table.tsx
  frontend/src/components/eam-configurate-group/components/permissions-table/permissions-table.tsx
  frontend/src/components/eam-configurate-group/components/workers-table/workers-table.tsx
  frontend/src/components/eam/components/groups-table/groups-table.tsx
  frontend/src/components/eam/components/workers-table/workers-table.tsx
  frontend/src/components/sc/components/instances-table/instance-table.tsx
  frontend/src/components/slc/components/functions-table/functions-table.tsx
Labels: enhancement

#151 BWS-148: + reload functionality to all tables
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/styles.module.scss
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/components/eam/styles.module.scss
  frontend/src/components/slc/slc.tsx
  frontend/src/components/slc/styles.module.scss
  frontend/src/store/eam-group-configurate/actions.ts
  frontend/src/store/eam-group-configurate/reducer.ts
  frontend/src/store/eam/actions.ts
  frontend/src/store/eam/reducer.ts
Labels: enhancement

#145 Task/bws 126 add run function functionality
  backend/package-lock.json
  backend/package.json
  backend/src/api/slc/slc.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/services/aws/lambda/lambda.service.ts
  backend/src/services/slc-function/slc-function.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/types/slc-function/slc-function.ts
  frontend/src/common/types/types.ts
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/button/styles.module.scss
  frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
  frontend/src/components/slc-configurate-function/components/edit-form/styles.module.scss
  frontend/src/helpers/helpers.ts
  frontend/src/helpers/timeout/timeout.ts
  frontend/src/services/slc-api/slc-api.service.ts
  frontend/src/store/slc-configurate-function/actions.ts
  frontend/src/store/slc-configurate-function/common.ts
  frontend/src/store/slc-configurate-function/reducer.ts
  shared/src/common/types/slc-function/slc-function-load-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function-run-params-dto.type.ts
  shared/src/common/types/slc-function/slc-function-run-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
  shared/src/helpers/helpers.ts
  shared/src/helpers/timeout/debounce.helper.ts
  shared/src/helpers/timeout/timeout.ts
Labels: enhancement

#158 Task/bws 97 fix palceholders
  frontend/src/components/eam-configurate-group/components/workers-table/workers-table.tsx
  frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
Labels: enhancement

#161 Task/bws 97 table placeholder text
  frontend/src/components/eam-configurate-group/components/workers-table/workers-table.tsx
Labels: enhancement

#155 Bws108 upload object to space
  backend/package-lock.json
  backend/package.json
  backend/src/api/api.ts
  backend/src/api/bs/bs.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/bs-object/bs-object-params.ts
  backend/src/common/types/bs-object/bs-object-upload-payload.type.ts
  backend/src/common/types/bs-object/bs-object.ts
  backend/src/common/types/object-upload/object-upload.ts
  backend/src/common/types/types.ts
  backend/src/data/models/bs-object/bs-object-table-field.enum.ts
  backend/src/data/models/bs-object/bs-object.model.ts
  backend/src/data/models/models.ts
  backend/src/data/repositories/bs-object/bs-object.repository.ts
  backend/src/data/repositories/repositories.ts
  backend/src/index.d.ts
  backend/src/middlewares/middlewares.ts
  backend/src/middlewares/upload/upload.middleware.ts
  backend/src/plugins/bs-object/bs-object.plugin.ts
  backend/src/plugins/plugins.ts
  backend/src/server.ts
  backend/src/services/aws/s3/s3.service.ts
  backend/src/services/bs-object/bs-object.entity.ts
  backend/src/services/bs-object/bs-object.service.ts
  backend/src/services/services.ts
  backend/src/services/space/space.service.ts
  shared/src/common/enums/api/spaces-api-path.enum.ts
  shared/src/common/types/object-upload/object-upload-request-params.dto.type.ts
  shared/src/common/types/object-upload/object-upload-request.dto.type.ts
  shared/src/common/types/object-upload/object-upload.ts
  shared/src/common/types/types.ts
Labels: enhancement

#157 Task/bws 105 permissions as list of chips
  frontend/src/assets/css/variables.scss
  frontend/src/assets/img/close-icon.svg
  frontend/src/assets/img/error-icon.svg
  frontend/src/assets/img/success-icon.svg
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/ui/chip-color.enum.ts
  frontend/src/common/enums/ui/chip-style.enum.ts
  frontend/src/common/enums/ui/icon-name.enum.ts
  frontend/src/common/enums/ui/ui.ts
  frontend/src/common/maps/maps.ts
  frontend/src/common/maps/ui/icon-name-to-src.map.ts
  frontend/src/common/maps/ui/ui.ts
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/chip/chip.tsx
  frontend/src/components/common/chip/styles.module.scss
  frontend/src/components/common/common.ts
  frontend/src/components/eam/components/groups-table/components/components.ts
  frontend/src/components/eam/components/groups-table/components/permissions-cell/permissions-cell.tsx
  frontend/src/components/eam/components/groups-table/helpers/get-rows.helper.ts
Labels: enhancement

#162 Task/bws142 download object
  backend/src/api/bs/bs.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/bs-object/bs-get-object-command-output.type.ts
  backend/src/common/types/bs-object/bs-object-params.ts
  backend/src/common/types/bs-object/bs-object.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/bs-object/bs-object.repository.ts
  backend/src/services/aws/s3/s3.service.ts
  backend/src/services/bs-object/bs-object.service.ts
  shared/src/common/enums/api/spaces-api-path.enum.ts
  shared/src/common/types/bs-object/bs-object.ts
  shared/src/common/types/bs-object/object-download-request-params.dto.type.ts
  shared/src/common/types/bs-object/object-upload-request-params.dto.type.ts
  shared/src/common/types/bs-object/object-upload-request.dto.type.ts
  shared/src/common/types/object-upload/object-upload-request-params.dto.type.ts
  shared/src/common/types/object-upload/object-upload.ts
  shared/src/common/types/types.ts
Labels: enhancement

#169 BWS-162: + change-edit-and-create-button-names-to-save
  frontend/src/components/bs-create-space/bs-create-space.tsx
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
  frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
  frontend/src/components/sc-configurate-instance/components/create-instance-form/create-instance-form.tsx
  frontend/src/components/sc-configurate-instance/components/update-instance-form/update-instance-form.tsx
  frontend/src/components/slc-configurate-function/components/create-form/create-form.tsx
Labels: enhancement

#168 BWS-159: + created-column-title-in-the-tables
  frontend/src/common/enums/bs/table/spaces-table-header.enum.ts
  frontend/src/common/enums/eam/table/groups-table-header.enum.ts
  frontend/src/common/enums/eam/table/pemissions-table-header.enum.ts
  frontend/src/common/enums/eam/table/users-table-header.enum.ts
  frontend/src/common/enums/eam/table/workers-table-header.enum.ts
  frontend/src/common/enums/sc/table/instances-table-accessor.enum.ts
  frontend/src/common/enums/sc/table/instances-table-header.enum.ts
  frontend/src/common/enums/slc/table/functions-table-header.enum.ts
Labels: enhancement

#173 Task/bws 144 fix table style
  frontend/src/components/common/table/styles.module.scss
Labels: enhancement

#170 BWS-167: + distance-from-the-field-to-validation-error-message
  frontend/src/components/common/input/styles.module.scss
Labels: enhancement

#174 Task/bws 141 pass arguments to slc function
  backend/src/api/slc/slc.api.ts
  backend/src/common/types/slc-function/slc-function.ts
  backend/src/common/types/types.ts
  backend/src/services/aws/lambda/lambda.service.ts
  backend/src/services/slc-function/slc-function.service.ts
  frontend/src/common/types/slc-function/slc-function.ts
  frontend/src/common/types/types.ts
  frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
  frontend/src/services/slc-api/slc-api.service.ts
  frontend/src/store/slc-configurate-function/actions.ts
  shared/src/common/types/slc-function/slc-function-run-request-dto.type.ts
  shared/src/common/types/slc-function/slc-function.ts
  shared/src/common/types/types.ts
Labels: enhancement

#175 BWS-165: + scroll-design
  frontend/src/assets/css/scaffolding.scss
Labels: enhancement

#184 BWS-174: * update-placeholders-and-labels
  frontend/src/components/common/select/select.tsx
  frontend/src/components/sc-configurate-instance/components/create-instance-form/create-instance-form.tsx
Labels: enhancement

#186 Task/bws 172 add modal component
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/event/event.ts
  frontend/src/common/enums/event/keydown-key.enum.ts
  frontend/src/components/common/common.ts
  frontend/src/components/common/modal/modal.tsx
  frontend/src/components/common/modal/styles.module.scss
Labels: enhancement

#190 BWS-160: + tooltips-on-hover-to-the-button-icons
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/components/spaces-table/components/action-cell/action-cell.tsx
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/icon-button/icon-button.tsx
  frontend/src/components/common/icon-button/styles.module.scss
  frontend/src/components/eam/components/groups-table/components/action-cell/action-cell.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/components/sc/components/instances-table/components/action-cell/action-cell.tsx
  frontend/src/components/sc/sc.tsx
  frontend/src/components/slc/components/functions-table/components/action-cell/action-cell.tsx
  frontend/src/components/slc/slc.tsx
Labels: enhancement

#178 Task/bws163 get objects endpoint
  backend/src/api/bs/bs.api.ts
  backend/src/common/types/bs-object/bs-object-params.ts
  backend/src/common/types/bs-object/bs-object-upload-payload.type.ts
  backend/src/common/types/bs-object/bs-object.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/bs-object/bs-object.repository.ts
  backend/src/services/bs-object/bs-object.service.ts
  shared/src/common/types/bs-object/bs-object-download-request-params.dto.type.ts
  shared/src/common/types/bs-object/bs-object-get-filter.type.ts
  shared/src/common/types/bs-object/bs-object-get-request-params.dto.type.ts
  shared/src/common/types/bs-object/bs-object-get-responce-item-dto.type.ts
  shared/src/common/types/bs-object/bs-object-get-response-dto.type.ts
  shared/src/common/types/bs-object/bs-object-upload-request-params.dto.type.ts
  shared/src/common/types/bs-object/bs-object-upload-request.dto.type.ts
  shared/src/common/types/bs-object/bs-object.ts
  shared/src/common/types/types.ts
Labels: enhancement

#167 Task/bws71 pagination for worker table
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/services/worker/worker.service.ts
  frontend/src/assets/img/arrow-left.svg
  frontend/src/assets/img/arrow-right.svg
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/pagination/pagination.enum.ts
  frontend/src/common/enums/pagination/pagination.ts
  frontend/src/common/enums/ui/icon-name.enum.ts
  frontend/src/common/maps/ui/icon-name-to-src.map.ts
  frontend/src/common/types/app/app.ts
  frontend/src/common/types/app/use-pagination-hook.type.ts
  frontend/src/common/types/types.ts
  frontend/src/components/common/table/table.tsx
  frontend/src/components/eam/components/workers-table/workers-table.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/components/pagination/pagination.tsx
  frontend/src/components/pagination/styles.module.scss
  frontend/src/hooks/hooks.ts
  frontend/src/hooks/use-pagination/use-pagination.hook.ts
  frontend/src/store/eam/reducer.ts
  shared/src/common/types/eam-worker/eam-worker-get-all-response-dto.type.ts
Labels: enhancement

#209 Task/BWS 190 remove resize icon paste line icon
  frontend/src/assets/img/resize.svg
  frontend/src/components/common/table/styles.module.scss
  frontend/src/components/common/table/table.tsx
Labels: enhancement

#210 BWS-160: * add-tooltips-on-hover-to-the-button-icons
  frontend/src/components/common/button/button.tsx
  frontend/src/components/common/link/link.tsx
Labels: enhancement

#211 BWS-71: * margin and size
  frontend/src/components/common/table/table.tsx
  frontend/src/components/pagination/styles.module.scss
Labels: enhancement

#206 Task/bws 185 pass arguments to the function custom popup
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/ui/editor-lang.enum.ts
  frontend/src/common/enums/ui/ui.ts
  frontend/src/common/maps/maps.ts
  frontend/src/common/maps/ui/lang-name-to-lang-extension.map.ts
  frontend/src/common/maps/ui/ui.ts
  frontend/src/components/common/editor/editor.tsx
  frontend/src/components/slc-configurate-function/components/edit-form/components/components.ts
  frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/slc-popup.tsx
  frontend/src/components/slc-configurate-function/components/edit-form/components/slc-popup/styles.module.scss
  frontend/src/components/slc-configurate-function/components/edit-form/edit-form.tsx
Labels: enhancement

#218 BWS-199: + tooltip-to-the-edit-button-on-the-groups-table-on-eam
  frontend/src/components/eam/components/groups-table/components/action-cell/action-cell.tsx
Labels: enhancement

#215 BWS-179: + apply-pagination-hook-for-all-tables
  backend/src/data/repositories/group/group.repository.ts
  backend/src/data/repositories/instance/instance.repository.ts
  backend/src/data/repositories/slc-function/slc-function.repository.ts
  backend/src/data/repositories/space/space.repository.ts
  backend/src/data/repositories/worker/worker.repository.ts
  backend/src/services/bs-object/bs-object.service.ts
  backend/src/services/group/group.service.ts
  backend/src/services/instance/instance.service.ts
  backend/src/services/slc-function/slc-function.service.ts
  backend/src/services/space/space.service.ts
  frontend/src/components/bs/components/spaces-table/spaces-table.tsx
  frontend/src/components/eam/components/groups-table/groups-table.tsx
  frontend/src/components/eam/components/workers-table/workers-table.tsx
  frontend/src/components/sc/components/instances-table/instance-table.tsx
  frontend/src/components/slc/components/functions-table/functions-table.tsx
  frontend/src/store/bs/reducer.ts
  frontend/src/store/eam/reducer.ts
  frontend/src/store/sc/reducer.ts
  frontend/src/store/slc/reducer.ts
  shared/src/common/types/bs-space/bs-space-get-response-dto.type.ts
  shared/src/common/types/eam-group/eam-group-get-by-tenant-response-dto.type.ts
  shared/src/common/types/sc-instance/sc-instance-get-by-tenant-response-dto.type.ts
  shared/src/common/types/slc-function/slc-function-get-response-dto.type.ts
Labels: enhancement

#230 Task/bws207 delete object functionality
  backend/src/api/bs/bs.api.ts
  backend/src/common/enums/exception/exception-message.enum.ts
  backend/src/common/types/bs-object/bs-object.ts
  backend/src/common/types/types.ts
  backend/src/data/repositories/bs-object/bs-object.repository.ts
  backend/src/services/aws/s3/s3.service.ts
  backend/src/services/bs-object/bs-object.service.ts
  frontend/src/common/enums/notification/notification-message.enum.ts
  frontend/src/common/types/bs-object/bs-object.ts
  frontend/src/common/types/types.ts
  frontend/src/components/bs-space/bs-space.tsx
  frontend/src/components/bs-space/components/objects-table/components/action-cell/action-cell.tsx
  frontend/src/components/bs-space/components/objects-table/components/action-cell/styles.module.scss
  frontend/src/components/bs-space/components/objects-table/helpers/get-rows.helper.ts
  frontend/src/components/bs-space/components/objects-table/objects-table.tsx
  frontend/src/services/bs-api/bs-api.service.ts
  frontend/src/store/bs-space/actions.ts
  frontend/src/store/bs-space/common.ts
  frontend/src/store/bs-space/reducer.ts
  shared/src/common/types/bs-object/bs-object-delete-params.dto.type.ts
  shared/src/common/types/bs-object/bs-object.ts
  shared/src/common/types/types.ts
Labels: merge conflicts

#231 BWS-215: + change-titles-on-the-edit-create-group-pages
  frontend/src/components/eam-configurate-group/components/permissions-table/permissions-table.tsx
  frontend/src/components/eam-configurate-group/components/workers-table/workers-table.tsx
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
Labels: enhancement

#228 Fix/bws 179 apply pagination hook for all tables
  frontend/src/common/types/app/use-pagination-hook.type.ts
  frontend/src/components/bs-space/bs-space.tsx
  frontend/src/components/bs-space/components/objects-table/objects-table.tsx
  frontend/src/components/bs-space/components/objects-table/styles.module.scss
  frontend/src/components/bs-space/styles.module.scss
  frontend/src/components/bs/bs.tsx
  frontend/src/components/bs/components/spaces-table/spaces-table.tsx
  frontend/src/components/bs/components/spaces-table/styles.module.scss
  frontend/src/components/bs/styles.module.scss
  frontend/src/components/eam-configurate-group/components/workers-table/workers-table.tsx
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
  frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
  frontend/src/components/eam/components/groups-table/groups-table.tsx
  frontend/src/components/eam/components/groups-table/styles.module.scss
  frontend/src/components/eam/components/workers-table/styles.module.scss
  frontend/src/components/eam/components/workers-table/workers-table.tsx
  frontend/src/components/eam/eam.tsx
  frontend/src/components/eam/styles.module.scss
  frontend/src/components/sc/components/instances-table/instance-table.tsx
  frontend/src/components/sc/components/instances-table/styles.module.scss
  frontend/src/components/sc/sc.tsx
  frontend/src/components/sc/styles.module.scss
  frontend/src/components/slc/components/functions-table/functions-table.tsx
  frontend/src/components/slc/components/functions-table/styles.module.scss
  frontend/src/components/slc/slc.tsx
  frontend/src/components/slc/styles.module.scss
  frontend/src/hooks/use-pagination/use-pagination.hook.ts
  frontend/src/store/bs/reducer.ts
  frontend/src/store/eam-group-configurate/reducer.ts
  frontend/src/store/eam-worker-configurate/reducer.ts
  frontend/src/store/eam/reducer.ts
  frontend/src/store/sc/reducer.ts
  frontend/src/store/slc/reducer.ts
Labels: enhancement

#240 BWS-215: * some text
  frontend/src/components/eam-configurate-group/eam-configurate-group.tsx
Labels: enhancement

#245 BWS-212: * previous-group-page-is-shown-after-opening-edit-group-page
  frontend/src/store/bs-space/reducer.ts
  frontend/src/store/bs/reducer.ts
  frontend/src/store/eam-group-configurate/reducer.ts
Labels: enhancement

#248 BWS-225: + the-placeholder-is-shown-under-the-loader-in-the-empty-table
  frontend/src/components/common/table/table.tsx
Labels: enhancement

#247 BWS-224: + pagination-is-shown-when-there-is-no-items-in-the-table
  frontend/src/components/common/table/table.tsx
  frontend/src/components/pagination/pagination.tsx
Labels: enhancement

#249 BWS-227: + data-testid-on-the-eam-page
  frontend/src/components/common/confirm-delete-popup/confirm-delete-popup.tsx
  frontend/src/components/eam-configurate-worker/eam-configurate-worker.tsx
Labels: enhancement
